name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Vulkan SDK
        id: cache-vulkan
        uses: actions/cache@v3
        with:
          path: VULKAN_SDK # The path to your Vulkan SDK installation directory
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true  
        if: steps.cache-vulkan.outputs.cache-hit != 'true'
        
      
      - name: Cache SDL3
        id: cache-sdl3
        uses: actions/cache@v3
        with:
          path: |
            SDL/build
            SDL/include
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          
      - name: Install SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          mkdir build && cd build
          cmake .. -DSDL_STATIC=ON
          cmake --build . --config Release
        if: steps.cache-sdl3.outputs.cache-hit != 'true'

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}-${{ hashFiles('**/lockfiles') }}

      - name: Install vcpkg
        env:
          VULKAN_SDK: ${{ github.workspace }}/VULKAN_SDK
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          vcpkg integrate install
          vcpkg install --triplet x64-windows vulkan freetype libpng[apng] harfbuzz fmt libwebp libjpeg-turbo libpng spdlog simdjson gtest libogg ffmpeg libavif curl
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
          

      # - name: Configure and build project
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake .. -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
      #     cmake --build .

      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest
