name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Cache and Install Dependencies
        id: cache-and-install
        uses: actions/cache@v2
        with:
          path: |
            VULKAN_SDK
            SDL/build
            SDL/include
            vcpkg
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
            
      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true  
        if: steps.cache-and-install.outputs.cache-hit != 'true'
          
      - name: Install SDL3
        run: |
          if (-Not (Test-Path "SDL")) {
            git clone https://github.com/libsdl-org/SDL
            cd SDL && mkdir build
            cd build && cmake .. -DSDL_STATIC=ON
            cmake --build . --config Release
          }
          
      - name: Install vcpkg
        env:
          VULKAN_SDK: ${{ github.workspace }}/VULKAN_SDK
        run: |
          if (-Not (Test-Path "vcpkg")) {
            git clone https://github.com/microsoft/vcpkg.git
            cd vcpkg && ./bootstrap-vcpkg.bat
            vcpkg integrate install
            vcpkg install --triplet x64-windows vulkan freetype libpng[apng] harfbuzz fmt libwebp libjpeg-turbo libpng spdlog simdjson gtest libogg ffmpeg libavif curl
          }
          

      # - name: Configure and build project
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake .. -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
      #     cmake --build .

      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest
