name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install Vulkan SDK
        run: |
          # Create a temporary directory to download the Vulkan SDK installer
          mkdir temp
          cd temp

          # Download the Vulkan SDK installer using curl
          curl -LO https://sdk.lunarg.com/sdk/download/1.3.250.1/windows/VulkanSDK-1.3.250.1-Installer.exe

          # Execute the installer to install Vulkan SDK
          # Replace "vulkan_sdk_installer.exe" with the actual installer name
          # and provide any necessary installation options if required
          .\VulkanSDK-1.3.250.1-Installer.exe

          # Clean up the temporary directory
          cd ..
          rmdir /s temp

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          vcpkg integrate install

      - name: Install dependencies
        run: |
          vcpkg install --triplet x64-windows vulkan freetype libpng[apng] harfbuzz fmt libwebp libjpeg-turbo libpng spdlog simdjson gtest libogg ffmpeg libavif curl

      - name: Configure and build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest
