name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Vulkan SDK
        id: cache-vulkan
        uses: actions/cache@v3
        with:
          path: VULKAN_SDK # The path to your Vulkan SDK installation directory
          key: ${{ runner.os }}-vulkan-${{ hashFiles('.github/workflows/rust.yml') }}

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.204.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true  
        if: steps.cache-vulkan.outputs.cache-hit != 'true'
 

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('.github/workflows/rust.yml') }}

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          vcpkg integrate install
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
          
#       - name: Cache vcpkg dependencies
#         id: cache-vcpkg-deps
#         uses: actions/cache@v2
#         with:
#           path: C:/path/to/installed/vcpkg/packages # The path where vcpkg installs its packages
#           key: ${{ runner.os }}-vcpkg-deps-${{ hashFiles('.github/workflows/rust.yml') }}
#         if: steps.cache-vcpkg-deps.outputs.cache-hit != 'true'

#       - name: Install dependencies
#         run: |
#           vcpkg install --triplet x64-windows vulkan freetype libpng[apng] harfbuzz fmt libwebp libjpeg-turbo libpng spdlog simdjson gtest libogg ffmpeg libavif curl

      # - name: Configure and build project
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake .. -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
      #     cmake --build .

      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest
